type: object
required:
  - id
  - name
  - slug
  - sourceRepoUrl
properties:
  id:
    type: string
    format: uuid
    readOnly: true
  name:
    type: string
    minLength: 2
    maxLength: 100
    readOnly: true
  slug:
    type: string
    pattern: '^[a-z0-9-]+$'
    minLength: 2
    maxLength: 100
    readOnly: true
  sourceWebsiteUrl:
    type: string
    format: uri
  sourceRepoUrl:
    type: string
    format: uri
  sourceBranch:
    type: string
    default: main
  lastCheckedAt:
    type: string
    format: date-time
    description: Last time the system checked for updates
    readOnly: true
  lastCommitHash:
    type: string
    description: Hash of the last processed commit
    readOnly: true
  description:
    type: string
    maxLength: 500
  isActive:
    type: boolean
    default: true
  createdAt:
    type: string
    format: date-time
    readOnly: true
  updatedAt:
    type: string
    format: date-time
    readOnly: true
